### ISSUE TITLE
feature request: add line between "pathSortOrder" groups

### ISSUE THREAD

**Issue by sasxa** [MLoughry/sort-typescript-imports#11]
Hi, nice work with this extension!

Could you add option to separate groups of imported modules with a blank line? It's easier to read when there are many imports...

```
import {...} from 'package'

import {...} from './../relativeUpLevel'

import {...} from './relativeDownLevel'
```

**Comment by MLoughry** [comment]
The [tslint rule around ordered imports](https://palantir.github.io/tslint/rules/ordered-imports/) treats each block of imports separated by a blank line as separate, and I have #8 open to handle them separately. Taken together, that means that sorting the imports, adding more, and re-sorting may continue to further and further fragment your import statements.

I'll take this under consideration after doing the work with #8 and #7. I could make it such that you can configure whether to treat different blocks separately, but I fear bloating the configuration even more.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
