### ISSUE TITLE
Better multiline imports format

### ISSUE THREAD

**Issue by Lxxyx** [MLoughry/sort-typescript-imports#15]
Before:
![image](https://cloud.githubusercontent.com/assets/13161470/24938554/7443a54e-1f6a-11e7-9f6a-4e7a6aab088c.png)

Formatted:
![image](https://cloud.githubusercontent.com/assets/13161470/24938548/68be7e38-1f6a-11e7-9793-6ccb6cd3f50b.png)

I think this is a better format for multiline imports.
![image](https://cloud.githubusercontent.com/assets/13161470/24938612/dd661caa-1f6a-11e7-80a8-341b02bdc9a2.png)

**Comment by Lxxyx** [comment]
And I have to say this project is awesome and helps me a lot. Thank you~

**Comment by artsyca** [comment]
As well, when sorting multi-line imports for a second time, all the multi-line blocks are placed at the bottom whereas they should be sorted in line with the others.

**Comment by neilsoult** [comment]
@Lxxyx FYI I forked this project since it wasn't being actively maintained and have incorporated this into my release. https://github.com/neilsoult/typescript-imports-sort

**Comment by Lxxyx** [comment]
@neilsoult Awesome works.
