### ISSUE TITLE
Improve sorting when Auto Save is on

### ISSUE THREAD

**Issue by stannynuytkens** [MLoughry/sort-typescript-imports#16]
Go ahead and try it out yourself... ;,,;

I think this will be a difficult thing to improve
because of the short lived time that vscode saves but
still I'd like your input on this.

**Comment by stannynuytkens** [comment]
As a workaround I've set `"typescript.extension.sortImports.sortOnSave": false` and sort manualy using ***F10***

**Comment by MLoughry** [comment]
What issues have you seen? It works fine in my experience.

**Comment by stannynuytkens** [comment]
Whenever I change something in my imports the line moves while typing.

**Comment by MLoughry** [comment]
Do you have `files.autoSave` set to `afterDelay` in your settings? That's the only thing I can think of that would cause something like that.

Otherwise, would you mind sharing  your user and workspace settings?

**Comment by stannynuytkens** [comment]
No I don't, I'll try that! 😉

**Comment by stannynuytkens** [comment]
This works for me but maybe you should warn the user if autosave is on because I'm not sure what the
default delay is...

`"files.autoSave": "afterDelay",
    "files.autoSaveDelay": 2000`
