### ISSUE TITLE
Support custom paths 

### ISSUE THREAD

**Issue by MartynasZilinskas** [MLoughry/sort-typescript-imports#18]
Support custom paths from `tsconfig.json`. It would nice to have additional type `customPath`. 
Example:
```json
{
    "compilerOptions": {
        "paths": {
            "@app/*": [
                "src/app/*"
            ]
        }
    }
}
```
Because, now this extensions thinks that it's a package name, which isn't.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
