### ISSUE TITLE
"Distinct Group" option

### ISSUE THREAD

**Issue by srcspider** [MLoughry/sort-typescript-imports#21]
For most of imports it's actually ideal for them to be bunched together. However there are a few cases where you want to split them apart for clarity. It would be nice if there was an option that essentially said: 

_"Any import types specified in this list should have a newline before them if there is another different group before them and a newline after if there is another different group after. No newline before if it's the first group. No newline after if it's the last group."_

eg.

```ts
"typescript.extension.sortImports.distinctGroups": [
  "package"  
]
```
If it's not on the list then obviously they just get bunched togheter.

_I would also add, just to re-emphasize, making everything be a distinct group all the time (ie. not having the option to select which have this rule) is bad and undesirable._

**Comment by sebastianqdot** [comment]
Not sure if related, but it would be nice to create blocks in such a way that the most common imports (i.e React por react apps) could be sorted as the first set of imports regardless of the selected pattern. 

Say you have 20 imports, you may want to sort them by path alphabetically, but it doesn't make sense to have React or any core dependency jumping positions from file to file. I much rather have it always at the top and then have the rest sorted.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
