### ISSUE TITLE
Wrong import order of index file in same folder

### ISSUE THREAD

**Issue by Xenya0815** [MLoughry/sort-typescript-imports#23]
**My configurations**

    "typescript.extension.sortImports.sortOnSave": true,
    "typescript.extension.sortImports.sortMethod": "path",
    "typescript.extension.sortImports.pathSortOrder": [
      "package",
      "relativeDownLevel",
      "relativeUpLevel"
    ]

**My imports**

    import Custom from '.';
    import * as mongoose from 'mongoose';

**Expected**
mongoose as first import, follwed from the import at the current project.

When I change the import to ` import Custom from './index' it works.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
