### ISSUE TITLE
Wrong import order with trailing comma

### ISSUE THREAD

**Issue by Xenya0815** [MLoughry/sort-typescript-imports#24]
**My configurations**

    "typescript.extension.sortImports.sortOnSave": true,
    "typescript.extension.sortImports.sortMethod": "path",
    "typescript.extension.sortImports.pathSortOrder": [
      "package",
      "relativeDownLevel",
      "relativeUpLevel"
    ]

**My imports**

    import {
      a, b, c,
      d, e, f,
    } from './a';
    import { x } from './b';

**Expected**
`./a` should be before `./b`. But the result is:

    import { x } from './b';
    import {
      a, b, c,
      d, e, f,
    } from './a';

If I remove the trailing comma after the `f` (my tslint configuration forces a trailling comma at multiline object), I get:

    import {
      a,
      b,
      c,
      d,
      e,
      f
      } from './a';
    import { x } from './b';

The order is now right (the indention of the closing bracket is wrong) but I can't add the trailling comma at the `f` manually, because then I get again the wrong order: 

    import { x } from './b';
    import {
      a,
      b,
      c,
      d,
      e,
      f,
      } from './a';

**Additional feature request**
I would be happy if I could specify a maximum line length instead of the maximum import number per line. For example, I have the following import:

    import { abcde, fghij, klmno, pqrst } from 'foo';

When I have configured the max line length to 20 (so a small number just for the example), I will get:

    import {
      abcde, fghij,
      klmno, pqrst
    } from 'foo';

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
