### ISSUE TITLE
Sort only selected imports

### ISSUE THREAD

**Issue by hassam7** [MLoughry/sort-typescript-imports#26]
A context menu which only sorts currently selected imports would be great improvement.
Thanks

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
