### ISSUE TITLE
Feature Request: Provide ability to remove the space in the brackets

### ISSUE THREAD

**Issue by mnp-mid** [MLoughry/sort-typescript-imports#27]
I like to use Visual Studio Code and some of my colleagues are using IntelliJ. However, IntelliJ is sorting the imports like this:

import **{UserService}** from "../../services/user.service";

This extension like this:
import **{ UserService }** from "../../common/services/user.service";

Please provide the ability to remove the leading and ending spaces in the brackets. This would be a lot of help.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
