### ISSUE TITLE
Option for allowing trailing commas

### ISSUE THREAD

**Issue by damiangreen** [MLoughry/sort-typescript-imports#28]
if I have an import with several  on one line, e.g. 4 or more:
`import {
  message,
  Upload,
  } from 'antd';`

with the option enabled to order on save:

` "typescript.extension.sortImports.sortOnSave": true`

it wraps multiple imports onto several lines and it then removes the trailing comma (after Upload) which causes my prettier file to complain

`import {
  message,
  Upload
  } from 'antd';`

So I have to disable sort on save for now :(

**Comment by neilsoult** [comment]
@damiangreen FYI I have forked this project since it was no longer actively maintained, and added your request to my latest release. https://github.com/neilsoult/typescript-imports-sort

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
