### ISSUE TITLE
ReactTypescript custom import rules options

### ISSUE THREAD

**Issue by d30jeff** [MLoughry/sort-typescript-imports#30]
Is there a way to customize the `pathSortOrder` option to achieve this?

```
import './EditPortfolioModal.scss';
import * as moment from 'moment-timezone';
import * as React from 'react';
import { Form, Row, Col, Input } from 'reactstrap';

import DeleteModal from '@components/common/DeleteModal/DeleteModal';
import EditModal from '@components/common/EditModal/EditModal';
import MonthPicker from '@components/common/MonthPicker/MonthPicker';

import CookieService from '@helpers/CookieService';
import MomentService from '@helpers/MomentService';
import providePortfolioProps, { PortfolioProps } from '@shared/connectors/Portfolio';
import { default as PortfolioModel } from '@shared/models/Portfolio';
```

1. Files that end with `.scss/.css`
2. Files that do not start with `.`
3. Files that contain symbols.
4. Rest of files that start with `.`

**Comment by d30jeff** [comment]
Duplicate of #5 

Closing

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
