### ISSUE TITLE
Feature Request: Support for .vue files

### ISSUE THREAD

**Issue by rothsandro** [MLoughry/sort-typescript-imports#31]
It would be nice to have support for .vue files when using the [Vue framework](https://vuejs.org).

There are (at least) two special cases to care about:

- The script tag may contain JS instead of TS (no lang attribute)
- The script tag may be missing if the component just has a template

Example of a .vue file:
```
<template>
  <div>...</div>
</template>

<script lang="ts">
import Vue from 'vue';
...
</script>

<style lang="scss" scoped>
div { ... }
</style>
```

**Comment by farzadmf** [comment]
Too bad there has been no comment on this. I really like this extension, and I'm recently working with Vue

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
