### ISSUE TITLE
Triple slash directives are placed after the imports when sorting

### ISSUE THREAD

**Issue by jpmnteiro** [MLoughry/sort-typescript-imports#33]
Hey, thank you the extension, it's amazing!

However, I came across a small problem. Take this example:

```
/// <reference path="../node_modules/ts-nameof/ts-nameof.d.ts" />

import moment from 'moment';
import { Action } from 'redux';
```

After sorting:

```
import moment from 'moment';
import { Action } from 'redux';
/// <reference path="../node_modules/ts-nameof/ts-nameof.d.ts" />
```

Typescript now longer recognises the triple slash properly because it has been placed after the imports. If there anything that can be done about this?

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
