### ISSUE TITLE
Allow to set max line lenght to move imports to new lines

### ISSUE THREAD

**Issue by Karolis92** [MLoughry/sort-typescript-imports#35]
Would be great to have `typescript.extension.sortImports.maxNamedImportsInSingleLine` alternative where it is possible to enter maximum line length instead of count of items.

Right now if imports have longer name I get tslint error for max line length.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.

**Comment by Karolis92** [comment]
Bundled organizer puts everything in one line. This is the main reason why I use this plugin...
