### ISSUE TITLE
Shebangs are moved after imports

### ISSUE THREAD

**Issue by edgarogh** [MLoughry/sort-typescript-imports#37]
When I sort a file that starts with a shebang, the shebang is moved after the imports, thus making the syntax incorrect.

Given this file:
```typescript
#!/usr/bin/env node
import chalk from 'chalk';
import program from 'commander';

program
    .version(require('../package.json').version);
```

If I try to save the file, I end up with:
```typescript
import chalk from 'chalk';
import program from 'commander';
#!/usr/bin/env node

program
    .version(require('../package.json').version);
```
...which is invalid JS/TS syntax (and is not understood by linux anyways). Because of this, I must disable the extension on all node cli projects.

**Fix suggestion (also fixes #33 and file-scoped/top-level JSDoc comments):**
When sorting a file, try to figure out a group of import statements and only rearrange imports inside this block without touching everything around it. In my example, I've surrounded the group of imports with square brackets:
```typescript
#!/usr/bin/env node
[import chalk from 'chalk';
import program from 'commander';]

program
    .version(require('../package.json').version);
```
Import should only be sorted "inside" my square-bracket-surrounded block of text. Everything before stays as-is.

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.

**Comment by edgarogh** [comment]
I didn't know about Typescript's own import organizer. I've switched to it and everything works fine. Thanks for answering!
