### ISSUE TITLE
imports in braces should be sorted too

### ISSUE THREAD

**Issue by JerryGreen** [MLoughry/sort-typescript-imports#38]
Currently it does not sort imports within `{ ... }`:

![image](https://user-images.githubusercontent.com/13215662/56866192-f3ce6200-69ef-11e9-830d-734f28942a80.png)

**Comment by MLoughry** [comment]
With the release of [Typescript 2.8](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-2/#organize-imports) over a year ago, the ability to organize imports comes bundled with Typescript, in a better implementation than this one made for a hack week. As such, I have no further plans to maintain this project.

If for whatever reason you would like to take ownership of this repository, please let me know.
