### ISSUE TITLE
Parse rules from `tslint.json`

### ISSUE THREAD

**Issue by MLoughry** [MLoughry/sort-typescript-imports#7]
The extension should look for a `tslint.json` configuration, and use its [`ordered-inputs`](https://palantir.github.io/tslint/rules/ordered-imports/) rule if present.

Also add configuration for a custom location for the configuration file, as well as a way to disable using the tslint config.

**Comment by DorianListens** [comment]
+1 this would be great! Getting the two to agree can be seriously challenging.
